### PR TITLE
depreciate the use of env var names with dots

### PR DESCRIPTION
**Pull request by krasi-georgiev**
closes: https://github.com/brocaar/lora-app-server/issues/369

show a warning when using var names with dots and replace those with the
underscore versions.
The config are now bind to the underscore env name versions.

cc @brocaar  lucky enough there is a nice workaround for providing the env name to which you want to bind a given config name.
Tested it locally and this change will not brake existing compose installations will just show a warning. 

Signed-off-by: Krasi Georgiev <8903888+krasi-georgiev@users.noreply.github.com>

### CODE REVIEW

**Comment by brocaar** [comment]
One comment, could you remove the `fmt.Println(d[0])` (I think that was there for testing purposes, but is not intended to be there)? The rest looks good to me :+1: 

Could you make a pull-request for the other components too to add this feature? That would be great :)

**Comment by krasi-georgiev** [comment]
oops sorry, updated

yes I will definitely add this change to all projects.

**Comment by krasi-georgiev** [comment]
ping @brocaar

**Comment by brocaar** [comment]
@krasi-georgiev sorry for the delay. I have been really busy with the ChirpStack migration which was announced last weekend and wanted to have that out before merging new changes.

See also: https://forum.chirpstack.io/t/rename-to-chirpstack-announcement/6473.

**Pull request merged**
