### PR TITLE
Add TX Ack events support to PostgreSQL integration

### PR DESCRIPTION
**Pull request by moutoum**
Good morning,

I added the TX Ack event for postgresql integration. I did it in a simple way, maybe I miss some fields or you had in mind more info to add. Do not hesitate to add a message if you have any comments.

One question : how do you handle the documentation part ?

Thanks,
Maxence

### CODE REVIEW

**Comment by brocaar** [comment]
Thanks @moutoum, I agree this is good to add. Would you mind moving your SQL migrations to `0003_tx_ack.up.sql` and `...down.sql`?

The idea with the SQL migrations is not to add to existing ones, but instead create new ones :-)

**Comment by sagar-patel-sls** [comment]
@brocaar @moutoum 
is it good to add whole `txinfo` in PostgreSQL Integration.

**Comment by moutoum** [comment]
@brocaar I changed the SQL migration, but I don't get why you don't want to use "IF NOT EXISTS" and "IF EXISTS" ?

**Comment by brocaar** [comment]
Thanks @moutoum, the reason is that the migration library keeps state of which migrations have been applied and which once not. Therefore a migration is never executed twice, unless something is wrong. When you are using `if not exists` / `if exists` then these issues are hidden as it becomes possible to run the migrations multiple times, without failing.

**Comment by brocaar** [comment]
@sagar-patel-sls @moutoum I'll look into the `tx_info` implementation. There are some other things to cleanup to implement this properly as it should respect the `marshaler` option. The PostgreSQL integration code wasn't touched for a while, I think now is a good time to clean this up and make sure it is aligned with the rest :)

**Pull request merged**
