### PR TITLE
Refactor SQL schema migrations from sql-migrate to golang-migrate.

### PR DESCRIPTION
**Pull request by sagar-patel-sls**
Refactor the code that uses sql-migrate using `github.com/golang-migrate/migrate/v4/cmd/migrate`

@brocaar Please review this change 
can you please check why the test cases failed?

I have tested this migration with the exiting database I have attached the below logs for your reference

```
time="2021-04-01T12:44:56+05:30" level=info msg="starting ChirpStack Application Server" docs="https://www.chirpstack.io/" version=3.14.0-18-g52792ee
time="2021-04-01T12:44:56+05:30" level=info msg="storage: setting up storage package"
time="2021-04-01T12:44:56+05:30" level=info msg="storage: setup metrics"
time="2021-04-01T12:44:56+05:30" level=info msg="storage: setting up Redis client"
time="2021-04-01T12:44:56+05:30" level=info msg="storage: connecting to PostgreSQL database"
time="2021-04-01T12:44:57+05:30" level=info msg="migrations/code: migrating from gorp_migrations to schema_migrations" golang_schema_migrations_version=58 gorp_migrations_id=0058_gateway_service_profile.sql
time="2021-04-01T12:44:57+05:30" level=info msg="storage: applying PostgreSQL data migrations"
time="2021-04-01T12:44:57+05:30" level=info msg="integration: configuring global integrations"
time="2021-04-01T12:44:57+05:30" level=info msg="integration/mqtt: TLS config is empty"
time="2021-04-01T12:44:57+05:30" level=info msg="integration/mqtt: connecting to mqtt broker" server="tcp://localhost:1883"
time="2021-04-01T12:44:57+05:30" level=info msg="integration/postgresql: connecting to PostgreSQL database"
time="2021-04-01T12:44:57+05:30" level=info msg="integration/mqtt: connected to mqtt broker"
time="2021-04-01T12:44:57+05:30" level=info msg="integration/mqtt: subscribing to tx topic" qos=0 topic=application/+/device/+/tx
time="2021-04-01T12:44:58+05:30" level=info msg="integration/postgresql: applying PostgreSQL schema migrations"
time="2021-04-01T12:44:59+05:30" level=info msg="integration/postgresql: applied database migrations" from_version=2 to_version=4
time="2021-04-01T12:44:59+05:30" level=info msg="api/as: starting application-server api" bind="0.0.0.0:8001" ca_cert= tls_cert= tls_key=
time="2021-04-01T12:44:59+05:30" level=info msg="api/external: starting api server" bind="0.0.0.0:8080" tls-cert= tls-key=
time="2021-04-01T12:44:59+05:30" level=info msg="api/external: registering rest api handler and documentation endpoint" path=/api
time="2021-04-01T12:44:59+05:30" level=info msg="api/js: starting join-server api" bind="localhost:8003" ca_cert= tls_cert= tls_key=
```
**Can we use `go:embed` for static(UI) files migration?**

### CODE REVIEW

**Comment by brocaar** [comment]
@sagar-patel-sls I have made some updates to the code. The tests were failing because some of these code migrations make API calls to the NS (for which an NS mock must be setup first). I have moved some of the code mgirations to the `root_run.go` and have kept the gorp to golang migration in the `storage.Setup` function.

Previously the PostgreSQL Integration was sharing the database with the other tests. I have fixed this as the schema migrations collide (the PostgreSQL integration was complaining that migration 58 does not exist, because that migration comes from the AS itself).

**Comment by brocaar** [comment]
> Can we use go:embed for static(UI) files migration?

Yes please! :)

**Comment by sagar-patel-sls** [comment]
> Yes please! :)

Can you please give me hint about this so I can work on this?

**Comment by brocaar** [comment]
@sagar-patel-sls I had to dive into this too, but it was quite easy, see above commit.

**Comment by brocaar** [comment]
Thanks for all this work @sagar-patel-sls :+1:

**Pull request merged**
