### PR TITLE
InfluxDB V2 Integration

### LINKED ISSUE #409: InfluxDB 2.0 integration support
InfluxDB 2.0 is now in Alpha and the writing API has changed slightly making it incompatible with the current integration.

from the influx 2.0 docs:
https://v2.docs.influxdata.com/v2.0/write-data/#influxdb-api

```
curl -XPOST "http://localhost:9999/api/v2/write?org=YOUR_ORG&bucket=YOUR_BUCKET&precision=s" \
    --header "Authorization: Token YOURAUTHTOKEN" \
    --data-raw "mem,host=host1 used_percent=23.43234543 1556896326" 
```
The biggest change appears to be the auth token header instead of basic auth/no auth from before, should not be too difficult to implement.

There does appear to be planned support in influx 2.0 for 1.0 style data writing according to their blog and theres a workaround using telegraf for now:

https://www.influxdata.com/blog/influxdb-2-migration-path-instrumentation/

### PR DESCRIPTION
**Pull request by wereii**
Depends on https://github.com/brocaar/chirpstack-api/pull/39

Resolves #409

I reused (read blatantly copied and pasted) a lot from V1 because the underlying protocol is same, only the way to connect to the database is different, I tried to make this visible by having that one commit with just pasted content so the next commit with the real feature has some sensible diff.
Maybe there is some way to reuse for example the go tests but I couldn't how to do it without exporting like almost whole file. It was simply more time efficient to copy paste the code instead of trying to find a way to extend the existing code (especially within go).

On frontend it's under the same integration (though within backend it is a different integration, so if needed these could be split so one application can have both V1 and V2 added)
image

### CODE REVIEW

**Comment by brocaar** [comment]
I'm not sure if this would be the way to go as it introduces a lot of unneeded duplication. Maybe copy&paste is a fast way to get things implemented, but don't forget it has to be maintained too :)

What I think would be needed is at the API level an `enum` with the InfluxDB version (who knows there might be a v3 in the future...) + the additional fields:

* `token`
* `organization`
* `bucket`

Then at the UI, when from the dropdown InfluxDB v1 is selected, we show:

* DB
* Username
* Password

If InfluxDB v2 is selected, we show:

* Token
* Organization
* Bucket


Then in the `func (i *Integration) send(...)` function based on the InfluxDB version we use the v1 `args` and optional basic auth header, or the v2 `args` + authorization header.

Did I overlook an other difference between v1 and v2?

**Comment by wereii** [comment]
You are right that this code is more on the the "fast & drity" side ˢᵒʳʳʸ.

I was afraid of extending the V1 with enum and two different possible "message formats" within one message because of database constraints (eg. if I need either of the formats but not mixed then having it all in one table would break as all the fields would have to be nullable and that's not reflecting the constraints in reality.. *one of the two but then all is required*).
Though now I see that these integration settings are not part of the underlying database schema (and I also opted into having it done faster, that one is indeed just on me:).

The difference between V1 and V2 is only in the information needed to successfully connect to the database and also instead of Basic Auth there is an Authorization header, so I think what you describe there works.

I will refactor this into enum instead of two integrations.

**Comment by brocaar** [comment]
@wereii I have implemented this in the above commit as I kept receiving requests for this (also for some of the projects that I support commercially). Thanks for making the initial attempt to implement this :)

**Comment by wereii** [comment]
Hey @brocaar thanks **to you** for implementing it - or well fixing my low effort PR in the first place:) sorry I didn't get to refactoring it.

**Pull request closed without merging**
