### PR TITLE
Implement API key feature

### PR DESCRIPTION
**Pull request by brocaar**
This feature makes it possible to generate (revokable) API keys that can be used to interact with the ChirpStack Application Server API.

- [x] Update API validator functions
- [x] API for generating admin API keys
- [x] API for generating organization API keys
- [x] API for generating application API keys
- [x] Web-interface component to generate admin API keys

### CODE REVIEW

**Comment by brocaar** [comment]
I will initially merge this without the (web-interface) option to generate organization and application API keys to get more feedback on this feature.

**Comment by tusharvb19** [comment]
Hello, 
How do we use these keys which we generate from app server under API key?

I follow this old process - 
call POST to internal login and get a token to use with all the API calls!

So what is the new in the API Key section added on app server?

Also, What is the expiry(if it is) for the token we get from POST to api/internal/login?

**Comment by brocaar** [comment]
You use them in the same way as the token obtained from `.../login`. The `.../login` token will automatically expire in 24 hours I believe, the API key token will be valid until revoked.

**Comment by tusharvb19** [comment]
But the thing is that I get error code 5 = object does not exist when I use the API key generated from App server to get service profiles! Rest works well.
Here is how you can repro:
1. Create a new API key and copy
2. Visit 8080/api
3. Try GET /api/service-profiles

**Comment by barnou** [comment]
Hello,

I can create an organization with the global api key but i can 't update it.

Can you tell me how to update it?

**Pull request merged**
