### PR TITLE
fix 'list service profiles' for API Key users

### PR DESCRIPTION
**Pull request by laher**
I can use API keys to list other entities such as organisations and network servers, so it seems unintended to prevent listing of service profiles.... This addresses a hard dependency on `validator.GetUser()` for this method.

* Currently, when I try to list service profiles with an API key, I get
 the following GRPC error message:
 	`rpc error: code = Unknown desc = subject must be user`
 * From other endpoints, I can see they mostly put calls to `GetUser()` behind a `GetSubject()` check, but ListServiceProfiles does not.
 * The code was last changed in May. Not sure if it was introduced then or beforehand: https://github.com/brocaar/chirpstack-application-server/commit/deddcade23ea78b0038fa86e2e244352727a6b96
 * This PR adds the `GetSubject()` check, and deals with the different code branches, appropriately AFAICT

### CODE REVIEW

**Comment by laher** [comment]
This addresses https://github.com/brocaar/chirpstack-application-server/issues/530

**Comment by sagar-patel-sls** [comment]
@laher @brocaar 
can we manage using the **filter** option to list service-profiles same as `storage.DeviceProfileFilters` in device-profile?

https://github.com/brocaar/chirpstack-application-server/blob/master/internal/api/external/device_profile.go#L302

**Comment by laher** [comment]
> @laher @brocaar
> can we manage using the **filter** option to list service-profiles same as `storage.DeviceProfileFilters` in device-profile?
> 
> [https://github.com/brocaar/chirpstack-application-server/blob/master/internal/api/external/device_profile.go#L302](https://github.com/brocaar/chirpstack-application-server/blob/master/internal/api/external/device_profile.go?rgh-link-date=2020-10-19T06%3A11%3A26Z#L302)

sounds like a good idea (although it's very much not my call). I think this request belongs in its own feature-request ticket, though. This PR is a bug-fix.

**Comment by laher** [comment]
@brocaar could you indicate if this PR is something you're open to reviewing and possibly merging, please? It's been open for a while now.

In the meantime I'm sharing JWT keys between my service and the app server, but it seems a bit of a shame.

Also, re. testing - since the original request, I added one test to confirm that api keys are accepted. I wonder if the bug (as I interpret it) is an indicator that API Keys are not well supported, and probably not widely used. I think more thorough tests are needed (in a follow-up PR, IMO), to ensure that API keys are supported across the external API. What do you think?

**Comment by brocaar** [comment]
@laher thanks for your work! However, now we are looking at changing this function, it might as well be a good opportunity to cleanup the storage functions as well. With the other storage functions I have slowly removed all the different  `GetXXXForUser`, `GetXXXForOrganizationID` etc... functions, in favor of generic `GetXXX` with an argument to pass a `XXXFilters` value.

See for example: https://github.com/brocaar/chirpstack-application-server/blob/master/internal/storage/application.go#L95 and https://github.com/brocaar/chirpstack-application-server/blob/master/internal/api/external/application.go#L185.

I believe this takes away some complexity and aligns this part of the code with the other parts :-) Would you be comfortable making this change?

**Comment by laher** [comment]
Yup, it looks reasonably straightforward and sensible. I'll do it next week.

I'm normally a big fan of keeping PRs small and having a single purpose, but I think I can see where you're both coming from, and I'm happy to help make the code better.

**Comment by laher** [comment]
@brocaar @sagar-patel-sls this is done now & tests are passing. Please take another look

**Comment by sagar-patel-sls** [comment]
Thanks to @laher 

@brocaar I think there is no need to do a filter based on `userid`

**Comment by brocaar** [comment]
Thanks @laher :+1:

**Pull request merged**
