### PR TITLE
Implement loader

### PR DESCRIPTION
**Pull request by sophiekovalevsky**
### Contribution description
Can be seen in https://github.com/brocaar/chirpstack-application-server/issues/492

- [x] Create loader component and store respectively
- [x] Insert dispatch loader actions as helper methods 
- [x] Don't show loader in fast api requests

### CODE REVIEW

**Comment by brocaar** [comment]
Hi @sophiekovalevsky thanks again for working on this :+1: I think this is a great contribution. I'm looking forward to merge this in!

I did encounter one issue, when a response returns a non 2xx code, then this doesn't stop the loader. This is because the counter is stopped / decremented just before calling the callback handling the response. However, the `checkStatus` function might throw an exception (https://github.com/brocaar/chirpstack-application-server/blob/master/ui/src/stores/helpers.js#L9) causing the decrement to never happen.

I think the loader decrement should happen before the `checkStatus` (maybe the increment / decrement could be implemented as helper function in `helpers.js`?)

One other improvement could be to show the loader after a certain threshold. For example 100ms (the actual number is something we should test). That way the loader does not show for fast requests :)

**Comment by sophiekovalevsky** [comment]
@brocaar thanks for reviewing this. 

I have updated the commit with changes that you requested. After several tests during weekend and I found out that  `stopLoader()` has to be called for every errorHandler aside before `checkStatus()` e.g. when I cleared my browser cache, ChirpStack Application Server tries to reach some pages from last session causing to throw 401 (Unauthorized), a similar behavior happens at Device details when activation has not been created yet throwing 404 (Not Found).

As regards to threshold value, I have added `showThreshold` so you can adapt based on your needs, I got smooth results when this value is 2, let me know if that value is reasonable for our use case.

**Comment by brocaar** [comment]
Thanks @sophiekovalevsky !!

**Comment by brocaar** [comment]
Unfortunately this breaks the web-interface sometimes (I think it is a race condition):

image

image


I'm reverting the merge for now. Would you be able to dig into this? And create a new PR?

**Pull request merged**
